# Generated by Django 4.1.3 on 2022-11-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "cod_empleado",
                    models.CharField(
                        max_length=6, primary_key="True", serialize=False, unique="True"
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("primer", models.CharField(max_length=30)),
                ("segundo", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=50)),
                ("extension", models.IntegerField()),
                ("fecha_nacimiento", models.DateField()),
                ("fecha_incorporacion", models.DateField()),
                ("discapacidad", models.CharField(max_length=2)),
                ("reduccion_jornada", models.CharField(max_length=2)),
                ("horas_jornada", models.IntegerField()),
            ],
        ),
    ]
