# Generated by Django 4.1.3 on 2022-11-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                ("cod_curso", models.CharField(max_length=6)),
                (
                    "nombre_curso",
                    models.CharField(
                        max_length=70,
                        primary_key="True",
                        serialize=False,
                        unique="True",
                    ),
                ),
                ("tipo_curso", models.CharField(max_length=20)),
            ],
        ),
    ]
