# Generated by Django 4.1.3 on 2022-11-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_usuarios", "0005_alter_empleado_cod_empleado_alter_empleado_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="delegacion",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
