# Generated by Django 4.1.3 on 2022-11-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_usuarios", "0006_empleado_delegacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="grupo_refuerzo",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="grupo_titular",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="servicio_refuerzo_1",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="servicio_refuerzo_2",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="servicio_titular",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
