# Generated by Django 4.1.3 on 2022-11-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_usuarios",
            "0007_empleado_grupo_refuerzo_empleado_grupo_titular_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="delegacion",
            field=models.CharField(max_length=30),
        ),
    ]
