# Generated by Django 4.1.3 on 2022-11-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_usuarios", "0008_alter_empleado_delegacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="grupo_titular",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="servicio_titular",
            field=models.CharField(max_length=30),
        ),
    ]
