# Generated by Django 4.1.3 on 2022-11-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_usuarios", "0010_formacion_curso"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="departamento",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="delegacion",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="grupo_titular",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
