# Generated by Django 4.1.3 on 2022-11-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_usuarios",
            "0011_empleado_departamento_alter_empleado_delegacion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="servicio_titular",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
