# Generated by Django 4.1.3 on 2022-11-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_usuarios", "0012_alter_empleado_servicio_titular"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="cod_curso",
            field=models.CharField(max_length=6, verbose_name="Código curso"),
        ),
        migrations.AlterField(
            model_name="curso",
            name="nombre_curso",
            field=models.CharField(
                max_length=70,
                primary_key="True",
                serialize=False,
                unique="True",
                verbose_name="Nombre del curso",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="tipo_curso",
            field=models.CharField(max_length=20, verbose_name="Tipo de curso"),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="primer",
            field=models.CharField(max_length=30, verbose_name="Primer apellido"),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="segundo",
            field=models.CharField(max_length=30, verbose_name="Segundo apellido"),
        ),
        migrations.AlterField(
            model_name="formacion",
            name="estado_curso",
            field=models.CharField(max_length=20, verbose_name="Estado"),
        ),
    ]
