# Generated by Django 4.1.3 on 2022-11-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_usuarios", "0014_correo"),
    ]

    operations = [
        migrations.DeleteModel(name="Correo",),
    ]
